# Multiple Linear Regression

## Importing the libraries

In [31]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [33]:
dataset = pd.read_csv('50_Startups.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [24]:
print(x)

[[165349.2 136897.8 471784.1 'New York']
 [162597.7 151377.59 443898.53 'California']
 [153441.51 101145.55 407934.54 'Florida']
 [144372.41 118671.85 383199.62 'New York']
 [142107.34 91391.77 366168.42 'Florida']
 [131876.9 99814.71 362861.36 'New York']
 [134615.46 147198.87 127716.82 'California']
 [130298.13 145530.06 323876.68 'Florida']
 [120542.52 148718.95 311613.29 'New York']
 [123334.88 108679.17 304981.62 'California']
 [101913.08 110594.11 229160.95 'Florida']
 [100671.96 91790.61 249744.55 'California']
 [93863.75 127320.38 249839.44 'Florida']
 [91992.39 135495.07 252664.93 'California']
 [119943.24 156547.42 256512.92 'Florida']
 [114523.61 122616.84 261776.23 'New York']
 [78013.11 121597.55 264346.06 'California']
 [94657.16 145077.58 282574.31 'New York']
 [91749.16 114175.79 294919.57 'Florida']
 [86419.7 153514.11 0.0 'New York']
 [76253.86 113867.3 298664.47 'California']
 [78389.47 153773.43 299737.29 'New York']
 [73994.56 122782.75 303319.26 'Florida']
 [67532

## Encoding categorical data

In [42]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [43]:
print(x)

  (0, 48)	1.0
  (0, 51)	1.0
  (0, 52)	136897.8
  (0, 53)	471784.1
  (1, 47)	1.0
  (1, 49)	1.0
  (1, 52)	151377.59
  (1, 53)	443898.53
  (2, 46)	1.0
  (2, 50)	1.0
  (2, 52)	101145.55
  (2, 53)	407934.54
  (3, 45)	1.0
  (3, 51)	1.0
  (3, 52)	118671.85
  (3, 53)	383199.62
  (4, 44)	1.0
  (4, 50)	1.0
  (4, 52)	91391.77
  (4, 53)	366168.42
  (5, 42)	1.0
  (5, 51)	1.0
  (5, 52)	99814.71
  (5, 53)	362861.36
  (6, 43)	1.0
  :	:
  (43, 51)	1.0
  (43, 52)	127382.3
  (43, 53)	35534.17
  (44, 6)	1.0
  (44, 49)	1.0
  (44, 52)	154806.14
  (44, 53)	28334.72
  (45, 2)	1.0
  (45, 51)	1.0
  (45, 52)	124153.04
  (45, 53)	1903.93
  (46, 3)	1.0
  (46, 50)	1.0
  (46, 52)	115816.21
  (46, 53)	297114.46
  (47, 0)	1.0
  (47, 49)	1.0
  (47, 52)	135426.92
  (48, 1)	1.0
  (48, 51)	1.0
  (48, 52)	51743.15
  (49, 0)	1.0
  (49, 49)	1.0
  (49, 52)	116983.8
  (49, 53)	45173.06


## Splitting the dataset into the Training set and Test set

In [55]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,y, test_size = 0.2,random_state =1)

In [56]:
print(x_train)

[[1.0 0.0 1.0 0.0 1.0 1.0 63408.86 129219.61 46085.25]
 [1.0 0.0 1.0 0.0 1.0 1.0 38558.51 82982.09 174999.3]
 [0.0 1.0 1.0 0.0 0.0 0.0 78389.47 153773.43 299737.29]
 [1.0 0.0 0.0 1.0 1.0 0.0 28663.76 127056.21 201126.82]
 [0.0 1.0 1.0 0.0 0.0 0.0 86419.7 153514.11 0.0]
 [1.0 0.0 1.0 0.0 1.0 1.0 23640.93 96189.63 148001.11]
 [1.0 0.0 1.0 0.0 1.0 1.0 0.0 116983.8 45173.06]
 [1.0 0.0 0.0 1.0 1.0 0.0 75328.87 144135.98 134050.07]
 [1.0 0.0 0.0 1.0 1.0 0.0 73994.56 122782.75 303319.26]
 [1.0 0.0 1.0 0.0 1.0 1.0 91992.39 135495.07 252664.93]
 [1.0 0.0 0.0 1.0 1.0 0.0 27892.92 84710.77 164470.71]
 [0.0 1.0 1.0 0.0 0.0 0.0 94657.16 145077.58 282574.31]
 [0.0 1.0 1.0 0.0 0.0 0.0 1000.23 124153.04 1903.93]
 [0.0 1.0 1.0 0.0 0.0 0.0 77044.01 99281.34 140574.81]
 [1.0 0.0 0.0 1.0 1.0 0.0 67532.53 105751.03 304768.73]
 [1.0 0.0 0.0 1.0 1.0 0.0 142107.34 91391.77 366168.42]
 [1.0 0.0 0.0 1.0 1.0 0.0 55493.95 103057.49 214634.81]
 [1.0 0.0 0.0 1.0 1.0 0.0 119943.24 156547.42 256512.92]
 [1.0 0.0 0.0 

## Training the Multiple Linear Regression model on the Training set

In [66]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

## Predicting the Test set results

In [67]:
y_pred = regressor.predict(x_test)

In [68]:
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[114664.42 105008.31]
 [ 90593.16  96479.51]
 [ 75692.84  78239.91]
 [ 70221.89  81229.06]
 [179790.26 191050.39]
 [171576.92 182901.99]
 [ 49753.59  35673.41]
 [102276.66 101004.64]
 [ 58649.38  49490.75]
 [ 98272.03  97483.56]]
